ignore_merge_commits = false

[changelog]
path = "CHANGELOG.md"
authors = [
  { signature = "Jonathan Irhodia", username = "elcharitas" }
]

[packages]
ngyn = { path = "crates/core" }
ngyn_cli = { path = "crates/cli" }
ngyn_macros = { path = "crates/macros" }
ngyn_shared = { path = "crates/shared" }
