[package]
name = "rustle_core"
version = "0.1.0"
edition = "2021"
lib = { path = "src/lib.rs" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nject = "0.3.0"
tide = "0.16.0"

