[package]
name = "ngyn-macros"
version = "0.4.0"
edition = "2021"
description = "Modular backend framework for web applications"
license = "MIT"

[dependencies]
syn = "2.0"
quote = "1.0"
ngyn-shared = { version = "^0.4.0", path = "../shared" }

[lib]
path = "src/lib.rs"
proc-macro = true
