[package]
name = "ngyn"
version = "0.3.0"
edition = "2021"
description = "Modular backend framework for web applications"
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
nject = "0.3.0"
ngyn_macros = { version = "0.3.0", path = "../macros" }
ngyn_shared = { version = "0.3.0", path = "../shared" }
tide = { version = "0.16.0", optional = true }
tokio = { version = "1", features = ["full"] }
vercel_runtime = { version = "1.1.0", optional = true }

[features]
tide = ["dep:tide"]
vercel = ["dep:vercel_runtime"]
